server.port=8085
spring.application.name=busbooking

# PostgreSQL (nên đổi cổng 5433 thành 5432 nếu cổng 5432 chưa được sử dụng)
spring.datasource.url=jdbc:postgresql://localhost:5433/busbooking
spring.datasource.username=busbooking_user
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
